[webs]
web01 ansible_host=192.168.234.102 ansible_connection=local
web02 ansible_host=192.168.234.103

[dbs]
vm-db01 ansible_host=192.168.234.101

[nfs]
vm-db01 ansible_host=192.168.234.101

[lbs]
web01 ansible_host=192.168.234.102 ansible_connection=local

[ha]
web01 ansible_host=192.168.234.102 ansible_connection=local keepalived_state=MASTER keepalived_priority=150
web02 ansible_host=192.168.234.103 keepalived_state=BACKUP keepalived_priority=100

[lnmp:children]
webs
dbs

[all:vars]
ansible_user=root
ansible_port=22
